const state={orders:[['#KB-1048','€129.90','Processing'],['#KB-1047','€59.00','Shipped'],['#KB-1046','€219.50','Delivered']],products:[['Smart Kitchen Device','€49.90','42 in stock'],['Wireless Headphones','€79.90','18 in stock'],['Home Storage Set','€29.90','7 in stock']],inventory:[['Smart Kitchen Device','42','OK'],['Wireless Headphones','18','OK'],['Home Storage Set','7','Low stock']]};
const screen=document.querySelector('#screen');
function money(n){return new Intl.NumberFormat('en-PT',{style:'currency',currency:'EUR'}).format(n)}
function dashboard(){return `<h1 class="title">Good morning 👋</h1><p class="muted">Kinbora business overview</p><div class="grid"><div class="card"><span class="muted">Today sales</span><div class="metric">${money(408.40)}</div></div><div class="card"><span class="muted">Orders</span><div class="metric">12</div></div><div class="card"><span class="muted">Customers</span><div class="metric">684</div></div><div class="card"><span class="muted">Low stock</span><div class="metric">3</div></div></div><div class="section">Recent orders</div><div class="list">${state.orders.map(o=>`<div class="row"><div><b>${o[0]}</b><div class="muted">${o[1]}</div></div><span class="pill">${o[2]}</span></div>`).join('')}</div><div class="section">Quick actions</div><div class="actions"><button class="btn" onclick="route('products')">Add product</button><button class="btn" onclick="route('inventory')">Update stock</button></div>`}
function orders(){return `<h1 class="title">Orders</h1><input class="search" placeholder="Search orders, customers or tracking"><div class="list">${state.orders.map(o=>`<div class="row"><div><b>${o[0]}</b><div class="muted">Customer order • ${o[1]}</div></div><span class="pill">${o[2]}</span></div>`).join('')}</div>`}
function products(){return `<h1 class="title">Products</h1><input class="search" placeholder="Search products or SKU"><div class="actions"><button class="btn">+ Add product</button><button class="btn">Categories</button></div><div class="list">${state.products.map(p=>`<div class="row"><div><b>${p[0]}</b><div class="muted">${p[1]} • ${p[2]}</div></div><span>›</span></div>`).join('')}</div>`}
function inventory(){return `<h1 class="title">Inventory</h1><input class="search" placeholder="Search SKU, barcode or product"><div class="list">${state.inventory.map(p=>`<div class="row"><div><b>${p[0]}</b><div class="muted">Stock: ${p[1]}</div></div><span class="pill">${p[2]}</span></div>`).join('')}</div>`}
function more(){const items=['Customers','Reports','Marketing','Coupons','Reviews','Returns & refunds','Suppliers','Purchase orders','Expenses','Support','Staff & permissions','Notifications','Settings','Audit logs'];return `<h1 class="title">Business tools</h1><div class="list">${items.map(x=>`<div class="row"><b>${x}</b><span>›</span></div>`).join('')}</div>`}
function route(r){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.route===r));screen.innerHTML={dashboard,orders,products,inventory,more}[r]();history.replaceState(null,'','#'+r)}
document.querySelectorAll('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>route(b.dataset.route)));document.querySelector('#notifyBtn').onclick=()=>alert('Notifications will connect to the Kinbora API.');route(location.hash.slice(1)||'dashboard');
