import React, {useEffect, useState} from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View, ActivityIndicator} from 'react-native';
import {StatusBar} from 'expo-status-bar';
import {SvgXml} from 'react-native-svg';

const LOGO = `<svg width="58" height="58" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><path d="M16 30h22l8 48H25L16 30Z" fill="#f28b32"/><path d="M23 30c1-12 8-18 17-18s16 6 17 18" fill="none" stroke="#f28b32" stroke-width="8" stroke-linecap="round"/><path d="M45 27l18 52h16L61 27H45Z" fill="#0d6b45"/><path d="M72 27L48 79h18l24-52H72Z" fill="#0d6b45"/><path d="M17 30h68" stroke="#f28b32" stroke-width="7" stroke-linecap="round"/><circle cx="27" cy="29" r="5" fill="#f28b32"/><circle cx="76" cy="29" r="5" fill="#f28b32"/></svg>`;
const DEMO_ORDERS=[['#KB-1042','Maria Silva','€129.90','Processing'],['#KB-1041','João Costa','€59.00','Shipped'],['#KB-1040','Ana Santos','€79.99','Delivered']];
const DEMO_PRODUCTS=[['Wireless Headphones','€39.99','24'],['Kitchen Blender','€59.00','8'],['Smart Watch','€79.99','3']];
const tools=['Marketing','Coupons','Reviews','Returns & Refunds','Shipping','Customers','Suppliers','Purchase Orders','Expenses & Profit','Support','Staff & Permissions','Notifications','Settings','Audit Logs'];
export default function App(){const [tab,setTab]=useState('Dashboard');const [api,setApi]=useState('');const [apiInput,setApiInput]=useState('');const [connected,setConnected]=useState(false);const [orders,setOrders]=useState(DEMO_ORDERS);const [products,setProducts]=useState(DEMO_PRODUCTS);const [loading,setLoading]=useState(false);useEffect(()=>{AsyncStorage.getItem('kinbora_api_url').then(v=>{if(v){setApi(v);setApiInput(v);loadData(v)}})},[]);async function loadData(base=api){if(!base)return;setLoading(true);try{const h={Accept:'application/json'};const [or,pr]=await Promise.all([fetch(base.replace(/\/$/,'')+'/api/orders.php',{headers:h}),fetch(base.replace(/\/$/,'')+'/api/products.php',{headers:h})]);if(!or.ok||!pr.ok)throw Error();const od=await or.json(),pd=await pr.json();setOrders(Array.isArray(od)?od.map(o=>[`#${o.id}`,o.billing?.first_name?`${o.billing.first_name} ${o.billing.last_name}`:'Customer',`€${o.total}`,o.status]):DEMO_ORDERS);setProducts(Array.isArray(pd)?pd.map(p=>[p.name,`€${p.price||'0'}`,String(p.stock_quantity??0)]):DEMO_PRODUCTS);setConnected(true)}catch(e){setConnected(false)}finally{setLoading(false)}}async function saveApi(){const v=apiInput.trim().replace(/\/$/,'');await AsyncStorage.setItem('kinbora_api_url',v);setApi(v);loadData(v)}return <SafeAreaView style={styles.safe}><StatusBar style="light"/><View style={styles.header}><SvgXml xml={LOGO} width={46} height={46}/><View><Text style={styles.brand}>Kinbora</Text><Text style={styles.subtitle}>Business Management</Text></View></View><ScrollView contentContainerStyle={styles.content}>{tab==='Dashboard'&&<Dashboard orders={orders} connected={connected} loading={loading}/>} {tab==='Orders'&&<Orders orders={orders}/>} {tab==='Products'&&<Products products={products}/>} {tab==='More'&&<More apiInput={apiInput} setApiInput={setApiInput} saveApi={saveApi} connected={connected} loading={loading}/>}</ScrollView><View style={styles.nav}>{['Dashboard','Orders','Products','More'].map(item=><TouchableOpacity key={item} style={styles.navItem} onPress={()=>setTab(item)}><Text style={[styles.navIcon,tab===item&&styles.active]}>{item==='Dashboard'?'⌂':item==='Orders'?'🛒':item==='Products'?'📦':'☰'}</Text><Text style={[styles.navText,tab===item&&styles.active]}>{item}</Text></TouchableOpacity>)}</View></SafeAreaView>}
function Dashboard({orders,connected,loading}){return <><View style={styles.hero}><SvgXml xml={LOGO} width={72} height={72}/><View><Text style={styles.muted}>Good morning</Text><Text style={styles.title}>Business Overview</Text></View></View><View style={styles.grid}><Metric label="Connection" value={connected?'LIVE':'DEMO'}/><Metric label="Orders" value={String(orders.length)}/><Metric label="Customers" value="—"/><Metric label="Low Stock" value="—"/></View><Text style={styles.section}>Recent Orders</Text><View style={styles.card}>{orders.map(o=><Row key={o[0]} title={o[0]} subtitle={`${o[1]} · ${o[2]}`} status={o[3]}/>)}</View>{loading&&<ActivityIndicator style={{margin:18}}/>}<View style={styles.notice}><Text style={styles.noticeTitle}>{connected?'Kinbora Store Connected':'Kinbora Store Not Connected'}</Text><Text style={styles.muted}>{connected?'Live WooCommerce data is being displayed.':'Open More → Store Connection and enter your deployed Kinbora API URL.'}</Text></View></>}
function Orders({orders}){return <><Text style={styles.title}>Orders</Text><View style={styles.card}>{orders.map(o=><Row key={o[0]} title={o[0]} subtitle={`${o[1]} · ${o[2]}`} status={o[3]}/>)}</View></>}
function Products({products}){return <><Text style={styles.title}>Products & Inventory</Text><View style={styles.card}>{products.map(p=><Row key={p[0]} title={p[0]} subtitle={`${p[1]} · Stock ${p[2]}`} status={Number(p[2])<5?'Low stock':'In stock'}/>)}</View></>}
function More({apiInput,setApiInput,saveApi,connected,loading}){return <><Text style={styles.title}>Business Tools</Text><View style={styles.card}><Text style={styles.connectionTitle}>Store Connection</Text><Text style={styles.muted}>Enter the URL where the PHP Kinbora API is deployed.</Text><TextInput value={apiInput} onChangeText={setApiInput} placeholder="https://api.example.com" autoCapitalize="none" keyboardType="url" style={styles.input}/><TouchableOpacity onPress={saveApi} style={styles.button}><Text style={styles.buttonText}>{loading?'Connecting…':'Save & Connect'}</Text></TouchableOpacity><Text style={[styles.connectionStatus,connected&&styles.connected]}>{connected?'● Connected':'○ Not connected'}</Text></View><View style={styles.card}>{tools.map(t=><View key={t} style={styles.tool}><Text style={styles.toolText}>{t}</Text><Text style={styles.arrow}>›</Text></View>)}</View></>}
function Metric({label,value}){return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>};function Row({title,subtitle,status}){return <View style={styles.row}><View style={{flex:1}}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.muted}>{subtitle}</Text></View><Text style={styles.pill}>{status}</Text></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#f5f7fb'},header:{backgroundColor:'#111827',paddingHorizontal:18,paddingTop:14,paddingBottom:14,flexDirection:'row',alignItems:'center',gap:10},brand:{color:'#fff',fontSize:22,fontWeight:'800'},subtitle:{color:'#cbd5e1',fontSize:12,marginTop:2},content:{padding:18,paddingBottom:110},hero:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:16},muted:{color:'#6b7280',fontSize:12},title:{color:'#111827',fontSize:26,fontWeight:'800',marginTop:4,marginBottom:18},section:{color:'#111827',fontSize:17,fontWeight:'800',marginTop:22,marginBottom:10},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},metric:{width:'47%',backgroundColor:'#fff',borderRadius:17,padding:16,borderWidth:1,borderColor:'#e8ecf2'},metricLabel:{color:'#6b7280',fontSize:12},metricValue:{color:'#111827',fontSize:23,fontWeight:'800',marginTop:5},card:{backgroundColor:'#fff',borderRadius:17,paddingHorizontal:16,borderWidth:1,borderColor:'#e8ecf2',marginBottom:14},row:{minHeight:66,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:'#eef1f5',gap:10},rowTitle:{color:'#111827',fontSize:14,fontWeight:'700',marginBottom:3},pill:{backgroundColor:'#eef2ff',color:'#3730a3',paddingHorizontal:9,paddingVertical:6,borderRadius:20,fontSize:10,fontWeight:'700'},notice:{marginTop:18,backgroundColor:'#fff',borderRadius:17,padding:16,borderWidth:1,borderColor:'#e8ecf2'},noticeTitle:{color:'#111827',fontSize:15,fontWeight:'800',marginBottom:5},tool:{minHeight:54,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:'#eef1f5'},toolText:{color:'#111827',fontSize:14,fontWeight:'600'},arrow:{color:'#9ca3af',fontSize:25},nav:{position:'absolute',bottom:0,left:0,right:0,height:76,backgroundColor:'#fff',borderTopWidth:1,borderTopColor:'#e5e7eb',flexDirection:'row',justifyContent:'space-around',paddingTop:9},navItem:{alignItems:'center',flex:1},navIcon:{fontSize:21,color:'#6b7280'},navText:{fontSize:10,color:'#6b7280',marginTop:3},active:{color:'#111827',fontWeight:'800'},connectionTitle:{fontSize:15,fontWeight:'800',color:'#111827',marginBottom:4},input:{borderWidth:1,borderColor:'#d1d5db',borderRadius:10,padding:12,marginTop:12,color:'#111827'},button:{backgroundColor:'#111827',borderRadius:10,padding:13,alignItems:'center',marginTop:10},buttonText:{color:'#fff',fontWeight:'800'},connectionStatus:{marginTop:10,color:'#b45309',fontWeight:'700'},connected:{color:'#15803d'}});
